import type { NextPage } from 'next'
import Head from 'next/head'
import { Card } from '@components'
import { StyledContainer } from './styles'
import { useQuery } from 'react-query'
import { GithubServices } from 'services'

const Home: NextPage = () => {
  const { isLoading, error, data } = useQuery('getUserRepos', () =>
    GithubServices.getUserRepos('MatheusChignolli')
  )

  if (isLoading) {
    return <>loading</>
  }

  if (error) {
    return <>error</>
  }

  if (!data || (!!data && !data?.length)) {
    return <>no data</>
  }

  return (
    <StyledContainer>
      <Head>
        <title>Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data.map((data: any) => (
          <Card key={`repo-${data.id}`}>
            <Card.Title>{data.visibility}</Card.Title>
            <Card.Content>
              {data.created_at} {data.language}
            </Card.Content>
            <Card.Link href={data.html_url}>{data.name}</Card.Link>
          </Card>
        ))}
      </main>
      <footer></footer>
    </StyledContainer>
  )
}

export default Home
